spring.application.name=t2g

logging.level.org.springframework.web=INFO
logging.level.org.hibernate=ERROR
logging.level.org.tauasa=DEBUG
logging.level.com.h2database=ERROR

springdoc.api-docs.path=/api-docs

# uncomment to generate ./sql/create.sql
# spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
# spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=./sql/create.sql
# spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-source=metadata

# postgres settings
spring.datasource.url=jdbc:postgresql://localhost:5432/t2g
spring.datasource.username=t2g
spring.datasource.password=t2g
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# management.endpoint.shutdown.enabled=true
# management.endpoints.web.exposure.include=health,info,shutdown
