spring.application.name=t2g

logging.level.org.springframework.web: INFO
logging.level.org.hibernate: ERROR
logging.level.org.tauasa: DEBUG

springdoc.api-docs.path=/api-docs

# management.endpoint.shutdown.enabled=true
# management.endpoints.web.exposure.include=health,info,shutdown
